name: 'PicoLisp Action'
description: 'Run 64-bit pil21 PicoLisp code'
author: 'AW <license@on-premises.com>'
branding:
  icon: 'code'
  color: 'purple'
inputs:
  version:
    description: 'The version of PicoLisp'
    required: false
    default: 'pil21'
  architecture:
    description: 'The architecture of PicoLisp (64-bit)'
    required: false
    default: 'src64'
runs:
  using: 'node12'
  main: 'dist/index.js'
